version: "3.9"
services: 
    api:
        build: "backend/brewery-api/."
        container_name: "brewery-api"
        ports: 
            - 8080:8080
        depends_on: 
            - "db"
    db:
        image: "postgres:alpine"
        container_name: "brewery-postgres"
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: brewery
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
    webpage:
        build: "frontend/."
        container_name: "webpage"
        ports:
            -80:80
            depends_on: 
                - "db"
                - "api"
    vm:
        image: "ubuntu"
        container_name: "test"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
volumes: 
    postgres-data: